<a href="https://colab.research.google.com/github/Yezz1n/first/blob/main/ESAA_first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 머신러닝:
애플리케이션 수정하지 않고도 데이터 기반으로 패턴 학습 후 결과 예측하는 알고리즘 기법
데이터 내의 패턴을 스스로 인지


---


###머신러닝의 분류:
*지도학습: 분류/회귀/추천 시스템/시각/음성감지/인지/텍스분석/NLP

*비지도학습:클러스터링/차원 축소/강화학습

+단점:데이터에 매우 의존적->'데이터 전쟁'

___

####파이썬 패키지:
머신러닝 패키지:사이킷런 

행렬/선형대수/통계 패키지:넘파이(행렬 데이터 특화),사이파이

데이터 핸들링:판다스(2차원 데이터 특화)

시각화:맷플롯립(효율 떨어짐),시본 


##넘파이




* 빠른 배열 연산 속도
* C/C++과 호환 가능한 API

* 2차원 형태의 행과 열

* 넘파이 기반 데이터 타입:ndarray

* as: 약어 표현

* array() :파이썬 의 리스트와 같은 다양한 인자 입력받아 ndarray로 변환 기능 

 + shape: ndarray의 크기. 행과 열의 수 튜플 형태로 가지고 있음->ndarray의 배열 차원까지 알 수 있다

* np.array():ndarray 반환

* ndarray.shape :ndarray의 차원의 크기 튜플 형태로 출력 (열,행)

In [ ]:
import numpy as np

array1=np.array([1,2,3]) #ndarray로 변환
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)


array2=np.array([[1,2,3],
                [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)


array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {:0} 차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1 차원, array2: 2차원, array3:  2차원


[]:1차원 [[]]:2차원

###ndarray의 데이터 타입
* ndarray 데이터 값: 모두 가능
ex)숫자형:int,unsigned int,float,complex

* ndarray 내의 데이터 타입: 같은 데이터 타입만 가능

 -> dtype 통해 데이터 타입 알 수 있다
 
 -> 섞이면 더 큰 데이터 타입으로 형 변환 일괄 적용


* astype(): ndarray 내 데이터 타입 변경

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


###ndarray 편리하게 생성하기-arange, zeros, ones


*arange(): range와 유사. 0~-1까지 index

In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)
#교재는 int32로 출력되는데 나는 자꾸 int64로 출력...

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


* zeros(): 함수 인자로 튜플 형태의 shape 값 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray로 반환


* ones(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환.


<font color='blue'>함수 인자로 dtype 정해주지않으면 default로 float64형의 데이터로 ndarray를 채움

In [ ]:
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


###reshape():ndarray의 차원, 크기 변경

reshape(): ndarray를 특정 차원 및 크기로 변환

->맞는 사이즈 아니면 오류 발생

In [ ]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


*-1인자는 reshape(-1,1)와 같은 형태로 사용
->반드시 1개의 컬럼 가진 ndarray로 변환

###인덱싱
-특정한 데이터만 추출

-슬라이싱[:]

-팬시 인덱싱:일정한 인덱싱 집합을 리스트나 ndarray형태로 지정하면, 해당 위치 index에 해당하는 ndarray 반환

-불린 인덱싱: T/F 값 인덱싱 집합으로 True 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환
조건 필터링과 검색 동시 가능


___



In [ ]:
array1d=np.arange(start=1,stop=10) #1부터 9 -->방향으로
array2d=array1d.reshape(3,3)
print(array2d)


#특정 값 추출
print('(row=0,col=0) index 가리키는 값:',array2d[0,0] )
print('(row=2,col=1) index 가리키는 값:',array2d[2,1] )


#슬라이싱(row,coloum)
print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])


#팬시 인덱싱
array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())
array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())


#불린 인덱싱
array5=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array5)
array1d>5


boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array6=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=2,col=1) index 가리키는 값: 8
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]
array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array1d>5 불린 인덱싱 결과 값: [6 7 8 9]
불린 인덱스로 필터링 결과: [6 7 8 9]


---

###행렬의 정렬:sort()&argsort()

* 행렬 정렬:

np.sort()-넘파이에서 sort() 호출

<font color='blue'>ex)np.sort('데이터명')


원 행렬 보존


ndarray.sort()-행렬 자체에서 sort() 호출 

<font color='blue'>ex)데이터명.sort()

원 행렬 자체가 정렬됨

반환값 None


=>내림차순 정렬 위해서는 [::-1]

axis=0:로우방향

axis=1:칼럼방향

In [ ]:
org_array=np.array([3,1,9,5])
sort_array1_desc=np.sort(org_array)[::-1]

print('내림차순으로 정렬:',sort_array1_desc)


array2d=np.array([[8,12],
                  [7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)

print('로우(행) 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n',sort_array2d_axis1)

내림차순으로 정렬: [9 5 3 1]
로우(행) 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]



* 원본 행렬 정렬 시 기존 원본 행렬의 원소가 필요하면 np.argsort() 이용

->정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

넘파이의 데이터 추출에 많이 사용


In [ ]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_desc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_desc])

성적 오름차순 정렬 시 score_array의 인덱스: [2 3 0 1]
성적 오름차순으로 name_array의 이름 출력: ['Sarah' 'Kate' 'John' 'Mike']



---
##선형대수 연산-행렬 내적과 전치 행렬
행렬내적은 행렬 곱
두 행렬 A와 B의 내적은 np.dot()활용->왼쪽 행렬의 행과 오른쪽 행렬의 열 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값

In [ ]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


전치 행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬

2x2 행렬 A가 있을 경우,A행렬의 1행 2열->2열 1행

A의 전치행렬==A**T


In [ ]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n',transpose_mat)


A의 전치 행렬:
 [[1 3]
 [2 4]]
